### ISSUE TITLE
Update to DataFrames 0.21

### ISSUE THREAD

**Issue by castrovjm** [jmboehm/GLFixedEffectModels.jl#10]
Hi! Thanks for developing this very useful packages.

I am trying to add it, however, I am getting the following error

```
(v1.3) pkg>  add https://github.com/jmboehm/GLFixedEffectModels.jl.git
  Updating git-repo `https://github.com/jmboehm/GLFixedEffectModels.jl.git`
  Updating git-repo `https://github.com/jmboehm/GLFixedEffectModels.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DataFrames [a93c6f00]:
 DataFrames [a93c6f00] log:
 ├─possible versions are: [0.11.7, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0-0.15.2, 0.16.0, 0.17.0-0.17.1, 0.18.0-0.18.4, 0.19.0-0.19.4, 0.20.0-0.20.2, 0.21.0-0.21.6] or uninstalled
 ├─restricted to versions 0.19-0.20 by GLFixedEffectModels [bafb0ae5], leaving only versions [0.19.0-0.19.4, 0.20.0-0.20.2]
 │ └─GLFixedEffectModels [bafb0ae5] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─GLFixedEffectModels [bafb0ae5] is fixed to version 0.1.0
 └─restricted to versions 0.21.6 by an explicit requirement — no versions left
 
```

**Comment by jmboehm** [comment]
Hi, it looks like you've pinned DataFrames.jl to 0.21.6 or have a package that depends on DataFrames 0.21.6, while GLFixedEffectModels is up to 0.20.0 only right now. I don't think there's much to do to update it to the most recent version, but I haven't done it yet...

**Comment by castrovjm** [comment]
Ok! Thanks so much. Glad to see your India paper finally in print. I ra’d a little bit in that project a couple of years ago.

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Johannes Boehm <notifications@github.com>
Enviado: Wednesday, August 12, 2020 12:24:53 PM
Para: jmboehm/GLFixedEffectModels.jl <GLFixedEffectModels.jl@noreply.github.com>
Cc: Juan Manuel Castro Vincenzi <castro.vincenzi@princeton.edu>; Author <author@noreply.github.com>
Asunto: Re: [jmboehm/GLFixedEffectModels.jl] Issue with Dataframes (#10)


Hi, it looks like you've pinned DataFrames.jl to 0.21.6 or have a package that depends on DataFrames 0.21.6, while GLFixedEffectModels is up to 0.20.0 only right now. I don't think there's much to do to update it to the most recent version, but I haven't done it yet...

**Comment by jmboehm** [comment]
Yes, I saw your comments on the draft. Thanks!

I'm tied down with revisions these days but hope to get back to this package some time in September. But feel free to submit a PR, if you need it earlier.
