### ISSUE TITLE
Dependency conflicts with Lasso.jl

### ISSUE THREAD

**Issue by caibengbu** [jmboehm/GLFixedEffectModels.jl#37]
Users might not be able download the latest version of GLFixedEffectModels (@0.3.1) with the presence of the package Lasso.

<img width="1013" alt="Screen Shot 2022-03-28 at 1 44 17 PM" src="https://user-images.githubusercontent.com/49098749/160391515-78b01e80-399a-4ce3-97f6-100f3b1edb2c.png">

With Lasso installed, an older version of GLFixedEffectModels (@0.1.3) is installed and this outdated precompiling script can't pass and will throw "weight not finite" error.

<img width="488" alt="Screen Shot 2022-03-28 at 1 30 22 PM" src="https://user-images.githubusercontent.com/49098749/160392054-fb2628e3-2cb4-49cc-b6a0-bab208e49761.png">

<img width="1012" alt="Screen Shot 2022-03-28 at 1 04 48 PM" src="https://user-images.githubusercontent.com/49098749/160391725-6befc7cf-17b4-4616-b346-fb729e0573c3.png">

A quick solution is to `pkg> rm Lasso`

**Comment by jmboehm** [comment]
Thanks. I guess we should allow versions of Distributions.jl that are above
0.24. I'll try to look into this this week.

**Comment by jmboehm** [comment]
Should be fixed in #39 (which now allows Distributions.jl 0.25), please re-open if not.
