### ISSUE TITLE
small comments

### ISSUE THREAD

**Issue by matthieugomez** [jmboehm/GLFixedEffectModels.jl#6]
Thanks for doing this package! It looks great.
Just two comments:
- It looks like you recreate fixed effects at each iteration (https://github.com/jmboehm/GLFixedEffectModels.jl/blob/master/src/fit.jl#L245). Does it take time? If so, maybe you could add an update_weights! method in FixedEffects.jl?
- It's your package but I think the name FixedEffectsGLM would be better (maybe I should switch to FixedEffectModels to FixedEffectsLM myself?)

**Comment by matthieugomez** [comment]
Also, if you want to add the package to the FixedEffects organization, you're welcome to. We can also give you writing access to FixedEffects / FixedEffectsModels if that makes things easier for you.

**Comment by jmboehm** [comment]
Thanks. Good point; I need to check that.

On the name of the package, I'm pretty indifferent. I doubt that it would make a big difference in terms of how easy it is for users to discover the package.

Probably makes sense to leave the package here for a few months to mature, and then put it into the FixedEffects organization.

**Comment by jmboehm** [comment]
You're right, it takes a bit of extra time to re-create the fixed effects in each iteration. I haven't digested the internals of FixedEffects.jl enough to check what update_weights! would need to do, but I'll look into it once the pile of papers to revise and to referee is a bit lighter :)
